package com.tonghannteng.todo.util

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF556423)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8EB9A)
val onPrimaryContainerLight = Color(0xFF3E4C0C)
val secondaryLight = Color(0xFF5B6146)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE0E6C4)
val onSecondaryContainerLight = Color(0xFF444930)
val tertiaryLight = Color(0xFF3A665E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBCECE1)
val onTertiaryContainerLight = Color(0xFF214E46)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBFAED)
val onBackgroundLight = Color(0xFF1B1C15)
val surfaceLight = Color(0xFFFBFAED)
val onSurfaceLight = Color(0xFF1B1C15)
val surfaceVariantLight = Color(0xFFE3E4D3)
val onSurfaceVariantLight = Color(0xFF46483C)
val outlineLight = Color(0xFF76786B)
val outlineVariantLight = Color(0xFFC7C8B8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303129)
val inverseOnSurfaceLight = Color(0xFFF2F1E5)
val inversePrimaryLight = Color(0xFFBCCE80)
val surfaceDimLight = Color(0xFFDBDBCF)
val surfaceBrightLight = Color(0xFFFBFAED)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F4E8)
val surfaceContainerLight = Color(0xFFEFEEE2)
val surfaceContainerHighLight = Color(0xFFE9E9DC)
val surfaceContainerHighestLight = Color(0xFFE4E3D7)

val primaryDark = Color(0xFFBCCE80)
val onPrimaryDark = Color(0xFF293500)
val primaryContainerDark = Color(0xFF3E4C0C)
val onPrimaryContainerDark = Color(0xFFD8EB9A)
val secondaryDark = Color(0xFFC4CAA9)
val onSecondaryDark = Color(0xFF2D331B)
val secondaryContainerDark = Color(0xFF444930)
val onSecondaryContainerDark = Color(0xFFE0E6C4)
val tertiaryDark = Color(0xFFA1D0C5)
val onTertiaryDark = Color(0xFF033730)
val tertiaryContainerDark = Color(0xFF214E46)
val onTertiaryContainerDark = Color(0xFFBCECE1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF13140D)
val onBackgroundDark = Color(0xFFE4E3D7)
val surfaceDark = Color(0xFF13140D)
val onSurfaceDark = Color(0xFFE4E3D7)
val surfaceVariantDark = Color(0xFF46483C)
val onSurfaceVariantDark = Color(0xFFC7C8B8)
val outlineDark = Color(0xFF909283)
val outlineVariantDark = Color(0xFF46483C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E3D7)
val inverseOnSurfaceDark = Color(0xFF303129)
val inversePrimaryDark = Color(0xFF556423)
val surfaceDimDark = Color(0xFF13140D)
val surfaceBrightDark = Color(0xFF393A31)
val surfaceContainerLowestDark = Color(0xFF0D0F08)
val surfaceContainerLowDark = Color(0xFF1B1C15)
val surfaceContainerDark = Color(0xFF1F2019)
val surfaceContainerHighDark = Color(0xFF292B23)
val surfaceContainerHighestDark = Color(0xFF34352D)

val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)